services:
  - type: web
    name: laravel-pos-kelompok7
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_NAME
        value: "POS Kelompok 7"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:+1knujeUckWgZfNW1Zy3/9XiOY9gJqJingpeiCXxzg4=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-pos-kelompok7.onrender.com

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: pos_jetstream
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your-password

      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: "POS Kelompok 7"

      - key: APP_TIMEZONE
        value: Asia/Jakarta
